apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-gateway
  labels:
    app: zomato-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zomato-gateway
  template:
    metadata:
      labels:
        app: zomato-gateway
    spec:
      containers:
        - name: zomato-gateway
          image: testing122/zomato-gateway:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8086

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8086
      protocol: TCP
  selector:
    app: zomato-gateway
