apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service-app
  labels:
    app: restaurant-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : restaurant-service-app
  template:
    metadata:
      labels:
        app: restaurant-service-app
    spec:
      containers:
      - name: restaurant-service-app
        image: testing122/restaurant-service:0.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8084

---

kind: Service
apiVersion: v1
metadata:
  name:  restaurant-service-svc
spec:
  selector:
    app:  restaurant-service-app
  ports:
  - port:  80
    targetPort:  8084
