apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-app-service
  labels:
    app: zomato-app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zomato-app-service
  template:
    metadata:
      labels:
        app: zomato-app-service
    spec:
      containers:
        - name: zomato-app-service
          image: testing122/auth-gateway:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: zomato-app-service-svc
spec:
  ports:
    - targetPort: 8081
      port: 80
  selector:
    app: zomato-app-service
